name: Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          passphrase: ${{ secrets.GCP_PASSPHRASE }}
          script: |
            cd /home/tve23cs131/stack-it-trial
            git fetch origin main
            git reset --hard origin/main
            docker compose up --build -d
